"""生产节点使用的稳定错误码。"""


TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
TOOL_INVALID_RESPONSE = "TOOL_INVALID_RESPONSE"
RAG_EXECUTION_ERROR = "RAG_EXECUTION_ERROR"
REPORT_GENERATION_ERROR = "REPORT_GENERATION_ERROR"
